<?php

namespace App\Console\Commands;

use App\Models\Announcement;
use App\Models\DocumentRequirement;
use App\Models\ImportBatch;
use App\Models\LiquidationComment;
use App\Models\LiquidationDocument;
use App\Models\Template;
use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;

class CleanOrphanedStorage extends Command
{
    protected $signature = 'storage:clean-orphans
                            {--dry-run : List files that would be deleted without actually deleting them}';

    protected $description = 'Delete storage files that have no matching database record';

    public function handle(): int
    {
        $dryRun = $this->option('dry-run');

        if ($dryRun) {
            $this->info('[DRY RUN] No files will be deleted.');
        }

        $totalDeleted = 0;
        $totalSize = 0;

        // --- 1. Liquidation documents ---
        $this->info('');
        $this->info('Scanning liquidation_documents/...');

        $knownPaths = LiquidationDocument::whereNotNull('file_path')
            ->where('is_gdrive', false)
            ->pluck('file_path')
            ->flip(); // use as set for O(1) lookup

        $files = Storage::disk('s3')->allFiles('liquidation_documents');

        foreach ($files as $file) {
            if (!$knownPaths->has($file)) {
                $size = Storage::disk('s3')->size($file);
                $totalSize += $size;
                $totalDeleted++;

                $this->line("  <fg=red>orphan:</> {$file} (" . $this->formatBytes($size) . ')');

                if (!$dryRun) {
                    Storage::disk('s3')->delete($file);
                }
            }
        }

        if (!$dryRun) {
            $this->pruneEmptyDirs('liquidation_documents');
        }

        // --- 2. Document requirement reference images ---
        $this->info('');
        $this->info('Scanning document_requirements/...');

        $knownImages = DocumentRequirement::whereNotNull('reference_image_path')
            ->pluck('reference_image_path')
            ->flip();

        $imageFiles = Storage::disk('s3')->allFiles('document_requirements');

        foreach ($imageFiles as $file) {
            if (!$knownImages->has($file)) {
                $size = Storage::disk('s3')->size($file);
                $totalSize += $size;
                $totalDeleted++;

                $this->line("  <fg=red>orphan:</> {$file} (" . $this->formatBytes($size) . ')');

                if (!$dryRun) {
                    Storage::disk('s3')->delete($file);
                }
            }
        }

        if (!$dryRun) {
            $this->pruneEmptyDirs('document_requirements');
        }

        // --- 3. Bulk-import source Excel files ---
        // Files land here from LiquidationController@bulkImportLiquidations.
        // They become orphans when an ImportBatch row is hard-deleted via raw
        // SQL or factory tearDown (the model observer handles ordinary deletes).
        $this->info('');
        $this->info('Scanning liquidation_imports/...');

        $knownImportPaths = ImportBatch::whereNotNull('file_path')
            ->pluck('file_path')
            ->flip();

        $importFiles = Storage::disk('s3')->allFiles('liquidation_imports');

        foreach ($importFiles as $file) {
            if (!$knownImportPaths->has($file)) {
                $size = Storage::disk('s3')->size($file);
                $totalSize += $size;
                $totalDeleted++;

                $this->line("  <fg=red>orphan:</> {$file} (" . $this->formatBytes($size) . ')');

                if (!$dryRun) {
                    Storage::disk('s3')->delete($file);
                }
            }
        }

        if (!$dryRun) {
            $this->pruneEmptyDirs('liquidation_imports');
        }

        // --- 4. Liquidation report exports (older than 7 days) ---
        // Generated by GenerateLiquidationReportJob and referenced only in
        // notification metadata. No DB row to cross-check — use age instead.
        $this->info('');
        $this->info('Scanning liquidation_reports/ (files older than 7 days)...');

        $cutoff = now()->subDays(7);
        $reportDiskName = (string) config('filesystems.reports', 'local');
        $reportDisk = Storage::disk($reportDiskName);
        $reportFiles = $reportDisk->allFiles('liquidation_reports');

        foreach ($reportFiles as $file) {
            $lastModified = $reportDisk->lastModified($file);
            if ($lastModified > $cutoff->timestamp) {
                continue;
            }

            $size = $reportDisk->size($file);
            $totalSize += $size;
            $totalDeleted++;

            $this->line("  <fg=red>expired:</> {$file} (" . $this->formatBytes($size) . ')');

            if (!$dryRun) {
                $reportDisk->delete($file);
            }
        }

        if (!$dryRun) {
            $this->pruneEmptyDirs('liquidation_reports', $reportDiskName);
        }

        // --- 5. User avatars ---
        $this->info('');
        $this->info('Scanning avatars/...');

        $knownAvatars = User::whereNotNull('avatar')
            ->pluck('avatar')
            ->flip();

        $avatarFiles = Storage::disk('s3')->allFiles('avatars');

        foreach ($avatarFiles as $file) {
            if (!$knownAvatars->has($file)) {
                $size = Storage::disk('s3')->size($file);
                $totalSize += $size;
                $totalDeleted++;

                $this->line("  <fg=red>orphan:</> {$file} (" . $this->formatBytes($size) . ')');

                if (!$dryRun) {
                    Storage::disk('s3')->delete($file);
                }
            }
        }

        // --- 6. Liquidation comment attachments ---
        $this->info('');
        $this->info('Scanning comment_attachments/...');

        $knownAttachments = LiquidationComment::whereNotNull('attachments')
            ->pluck('attachments')
            ->flatten(1)
            ->pluck('path')
            ->filter()
            ->flip();

        $attachmentFiles = Storage::disk('s3')->allFiles('comment_attachments');

        foreach ($attachmentFiles as $file) {
            if (!$knownAttachments->has($file)) {
                $size = Storage::disk('s3')->size($file);
                $totalSize += $size;
                $totalDeleted++;

                $this->line("  <fg=red>orphan:</> {$file} (" . $this->formatBytes($size) . ')');

                if (!$dryRun) {
                    Storage::disk('s3')->delete($file);
                }
            }
        }

        if (!$dryRun) {
            $this->pruneEmptyDirs('comment_attachments');
        }

        // --- 7. Announcement cover images ---
        $this->info('');
        $this->info('Scanning announcements/covers/...');

        $knownCovers = Announcement::query()
            ->select(['cover_original_path', 'cover_display_path', 'cover_thumb_path'])
            ->get()
            ->flatMap(fn($a) => array_filter([
                $a->cover_original_path,
                $a->cover_display_path,
                $a->cover_thumb_path,
            ]))
            ->flip();

        $coverFiles = Storage::disk('s3')->allFiles('announcements/covers');

        foreach ($coverFiles as $file) {
            if (!$knownCovers->has($file)) {
                $size = Storage::disk('s3')->size($file);
                $totalSize += $size;
                $totalDeleted++;

                $this->line("  <fg=red>orphan:</> {$file} (" . $this->formatBytes($size) . ')');

                if (!$dryRun) {
                    Storage::disk('s3')->delete($file);
                }
            }
        }

        if (!$dryRun) {
            $this->pruneEmptyDirs('announcements/covers');
        }

        // --- 8. Import templates ---
        $this->info('');
        $this->info('Scanning templates/...');

        $knownTemplates = Template::whereNotNull('file_path')
            ->pluck('file_path')
            ->flip();

        $templateFiles = Storage::disk('s3')->allFiles('templates');

        foreach ($templateFiles as $file) {
            if (!$knownTemplates->has($file)) {
                $size = Storage::disk('s3')->size($file);
                $totalSize += $size;
                $totalDeleted++;

                $this->line("  <fg=red>orphan:</> {$file} (" . $this->formatBytes($size) . ')');

                if (!$dryRun) {
                    Storage::disk('s3')->delete($file);
                }
            }
        }

        // --- Summary ---
        $this->info('');

        if ($totalDeleted === 0) {
            $this->info('No orphaned files found. Storage is clean.');
        } elseif ($dryRun) {
            $this->warn("[DRY RUN] Would delete {$totalDeleted} file(s) freeing " . $this->formatBytes($totalSize) . '.');
            $this->warn('Run without --dry-run to actually delete them.');
        } else {
            $this->info("Deleted {$totalDeleted} orphaned file(s), freed " . $this->formatBytes($totalSize) . '.');
        }

        return self::SUCCESS;
    }

    /**
     * Remove empty directories inside a given storage path.
     */
    private function pruneEmptyDirs(string $directory, string $diskName = 's3'): void
    {
        $disk = Storage::disk($diskName);
        foreach ($disk->directories($directory) as $dir) {
            if (empty($disk->allFiles($dir))) {
                $disk->deleteDirectory($dir);
                $this->line("  <fg=yellow>removed empty dir:</> {$dir}");
            }
        }
    }

    private function formatBytes(int $bytes): string
    {
        if ($bytes < 1024) return "{$bytes} B";
        if ($bytes < 1048576) return round($bytes / 1024, 1) . ' KB';
        return round($bytes / 1048576, 2) . ' MB';
    }
}
