<?php

namespace Database\Seeders;

use App\Models\HEI;
use App\Models\Region;
use Illuminate\Database\Seeder;

// php artisan db:seed --class=HEISeeder

class HEISeeder extends Seeder
{
    public function run(): void
    {
        // Look up regions by code — works correctly after every migrate:fresh
        $r12   = Region::where('code', 'R12')->first()?->id;
        $barmm = Region::where('code', 'BARMM')->first()?->id;

        $heis = [
            // ── Region 12 (SOCCSKSARGEN) ──────────────────────────────────
            ['uii' => '12120',   'name' => 'ACLC COLLEGE OF MARBEL',                                                   'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12131',   'name' => 'RAMON MAGSAYSAY MEMORIAL COLLEGES-MARBEL, INC.',                           'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12108',   'name' => "GENERAL SANTOS DOCTORS' MEDICAL SCHOOL FOUNDATION, INC.",                  'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12129',   'name' => 'STI COLLEGE KORONADAL CITY, INC. TACURONG BRANCH',                         'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12002',   'name' => 'CENTRAL MINDANAO COLLEGES',                                                'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12147',   'name' => 'MAKILALA INSTITUTE OF SCIENCE AND TECHNOLOGY',                             'type' => 'LUC',     'region_id' => $r12],
            ['uii' => '12086',   'name' => 'NORTH VALLEY COLLEGE FOUNDATION, INCORPORATED',                            'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12144',   'name' => 'GENSAN COLLEGE OF TECHNOLOGY, INC.',                                       'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12159',   'name' => 'GOLDENSTATE COLLEGE OF MALUNGON, INC.',                                    'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12150',   'name' => 'FILIPINO CANADIAN COMMUNITY COLLEGE FOUNDATION INCORPORATED',              'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11112',   'name' => 'STI COLLEGE - GEN. SANTOS , INC',                                          'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11029',   'name' => 'GENSANTOS FOUNDATION COLLEGE, INC.',                                       'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12114',   'name' => 'HOLY CHILD CENTRAL COLLEGES, INC.',                                        'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12127',   'name' => 'MARVELOUS COLLEGE OF TECHNOLOGY, INC.',                                    'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12008d',  'name' => 'COTABATO FOUNDATION COLLEGE OF SCIENCE AND TECHNOLOGY - PIKIT',            'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12074d',  'name' => 'SULTAN KUDARAT STATE UNIVERSITY - BAGUMBAYAN',                             'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12132',   'name' => 'GENERAL SANTOS ACADEMY, INCORPORATED',                                     'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11116',   'name' => 'MARBEL SCHOOL OF SCIENCE AND TECHNOLOGY,INC.',                             'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12153',   'name' => 'GLAN INSTITUTE OF TECHNOLOGY',                                             'type' => 'LUC',     'region_id' => $r12],
            ['uii' => '12122',   'name' => 'STI COLLEGE KORONADAL CITY, INC.',                                         'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11036',   'name' => 'HOLY TRINITY COLLEGE OF GENERAL SANTOS CITY',                              'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12045',   'name' => 'COLEGIO DE KIDAPAWAN',                                                     'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12163',   'name' => 'KING SOLOMON INSTITUTE, INC.',                                             'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12074a',  'name' => 'SULTAN KUDARAT STATE UNIVERSITY - ISULAN',                                 'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '11045',   'name' => 'MINDANAO POLYTECHNIC COLLEGE',                                             'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12064',   'name' => 'SENATOR NINOY AQUINO COLLEGE FOUNDATION, INC.',                            'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12148',   'name' => 'WEST CELEBES COLLEGE OF TECHNOLOGY INCORPORATED',                          'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12069',   'name' => 'SOUTHERN PHILIPPINES METHODIST COLLEGES, INC.',                            'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11057',   'name' => 'SCHOLA DE SAN JOSE, INC.',                                                 'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12051',   'name' => 'NOTRE DAME OF SALAMAN COLLEGE',                                            'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12074g',  'name' => 'SULTAN KUDARAT STATE UNIVERSITY - TACURONG',                               'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12171',   'name' => 'NORTH CIRCLE ACADEMY, INC.',                                               'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12168',   'name' => 'UST GENERAL SANTOS',                                                       'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11051',   'name' => 'NOTRE DAME OF DADIANGAS UNIVERSITY',                                       'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11106',   'name' => 'SOUTH COTABATO STATE COLLEGE',                                             'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12143',   'name' => 'KULAMAN ACADEMY INC.',                                                     'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12012',   'name' => 'DR. DOMINGO B. TAMONDONG MEMORIAL HOSPITAL & COLLEGE FOUNDATION, INC.',    'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12093',   'name' => 'CENTRAL MINDANAO COMPUTER SCHOOL., INC.',                                  'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12078',   'name' => 'UNIVERSITY OF SOUTHERN MINDANAO-MAIN',                                     'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12115',   'name' => 'SOUTH EAST ASIAN INSTITUTE OF TECHNOLOGY, INC.',                           'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12072',   'name' => 'SULTAN KUDARAT EDUCATIONAL INSTITUTION',                                   'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12165',   'name' => 'VMC ASIAN COLLEGE OF PRESIDENT QUIRINO, INC.',                             'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11048',   'name' => 'MINDANAO STATE UNIVERSITY - GENERAL SANTOS CITY',                          'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12025',   'name' => "KING'S COLLEGE OF ISULAN",                                                 'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12170',   'name' => 'SOUTH ASIATECH COLLEGE, INC.',                                             'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12151',   'name' => 'NEW ERA UNIVERSITY, GENERAL SANTOS CITY BRANCH',                           'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12124',   'name' => 'I-LINK COLLEGE OF SCIENCE AND TECHNOLOGY INC.',                            'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12074c',  'name' => 'SULTAN KUDARAT STATE UNIVERSITY - KALAMANSIG',                             'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '11059',   'name' => 'RAMON MAGSAYSAY MEMORIAL COLLEGES',                                        'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12031',   'name' => "LEBAK FAMILY DOCTORS' SCHOOL OF MIDWIFERY",                                'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12112',   'name' => 'BROKENSHIRE COLLEGE SOCCSKSARGEN, INC.',                                   'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12074',   'name' => 'SULTAN KUDARAT STATE UNIVERSITY',                                          'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12074b',  'name' => 'SULTAN KUDARAT STATE UNIVERSITY - LUTAYAN',                                'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '11052',   'name' => 'NOTRE DAME OF MARBEL UNIVERSITY',                                          'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12139',   'name' => 'VILLAMOR COLLEGE OF BUSINESS AND ARTS',                                    'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12119',   'name' => 'STRATFORD INTERNATIONAL SCHOOL',                                           'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12010',   'name' => 'COTABATO MEDICAL FOUNDATION COLLEGE, INCORPORATED',                        'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12146',   'name' => 'SOUTHPOINT COLLEGE OF ARTS AND TECHNOLOGY (SPAT), INC.',                   'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12138',   'name' => 'MMG COLLEGE OF GENERAL SANTOS CITY, INC.',                                 'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11081',   'name' => 'SANTA CRUZ MISSION SCHOOL, INC.',                                          'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12110',   'name' => 'NOTRE DAME-SIENA COLLEGE OF POLOMOLOK',                                    'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12005',   'name' => 'REGENCY POLYTECHNIC COLLEGE, INC',                                         'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12149',   'name' => 'SOUTH CENTRAL MINDANAO COLLEGE OF SCIENCE AND TECHNOLOGY, INC.',           'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12169',   'name' => 'MALAPATAN COLLEGE OF SCIENCE AND TECHNOLOGY',                              'type' => 'LUC',     'region_id' => $r12],
            ['uii' => '12158',   'name' => 'GOLDENSTATE COLLEGE OF MAASIM, INC.',                                      'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11113',   'name' => 'GREEN VALLEY COLLEGE FOUNDATION, INC.',                                    'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12166',   'name' => 'ENVIROGREEN SCHOOL OF TECHNOLOGY',                                         'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12126',   'name' => 'GOLDENSTATE COLLEGE OF KORONADAL CITY, INC.',                              'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12164',   'name' => 'SANTO NINO COLLEGE FOUNDATION, INC.',                                      'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12044',   'name' => 'UNIVERSITY OF SOUTHERN MINDANAO-KIDAPAWAN CITY CAMPUS',                    'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12117',   'name' => 'ASIAN COLLEGES AND TECHNOLOGICAL INSTITUTE, INC',                          'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12050',   'name' => 'NOTRE DAME OF MIDSAYAP COLLEGE',                                           'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12052',   'name' => 'NOTRE DAME OF TACURONG COLLEGE',                                           'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12068',   'name' => 'SOUTHERN MINDANAO INSTITUTE OF TECHNOLOGY, INC.',                          'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12157',   'name' => 'GOLDENSTATE COLLEGE OF KIAMBA, INC.',                                      'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12172',   'name' => 'UPM-SCHOOL OF HEALTH SCIENCES KORONADAL CAMPUS',                           'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12167',   'name' => 'NEW HOPE SCHOOL OF AGRICULTURE AND FISHERY, INC.',                         'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12140',   'name' => 'CRONASIA FOUNDATION COLLEGE, INC.',                                        'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11022',   'name' => 'ST. ALEXIUS COLLEGE, INC.',                                                'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12155',   'name' => 'SOUTHERN PHILIPPINE TECHNICAL COLLEGE OF KORONADAL, INCORPORATED',         'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12130',   'name' => 'B.E.S.T. COLLEGE OF POLOMOLOK, INC.',                                      'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12121',   'name' => 'KORBEL FOUNDATION COLLEGE, INC.',                                          'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12116',   'name' => 'VMC ASIAN COLLEGE FOUNDATION, INC.',                                       'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12074f',  'name' => 'SULTAN KUDARAT STATE UNIVERSITY - PALIMBANG',                              'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '11024',   'name' => 'EDENTON MISSION COLLEGE, INC.',                                            'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12104',   'name' => 'ADVENTIST COLLEGE OF TECHNOLOGY, INCORPORATED',                            'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12049',   'name' => 'NOTRE DAME OF KIDAPAWAN COLLEGE',                                          'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12008',   'name' => 'COTABATO FOUNDATION COLLEGE OF SCIENCE AND TECHNOLOGY',                    'type' => 'SUC',     'region_id' => $r12],
            ['uii' => '12067',   'name' => 'SOUTHERN CHRISTIAN COLLEGE',                                               'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12105',   'name' => 'GOLDENSTATE COLLEGE',                                                      'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12136',   'name' => 'JOJI ILAGAN INTERNATIONAL SCHOOL OF HOTEL AND TOURISM MANAGEMENT',         'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12145',   'name' => 'PRIMASIA FOUNDATION COLLEGE, INC.',                                        'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12142',   'name' => 'KIDAPAWAN DOCTORS COLLEGE, INCORPORATED',                                  'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12160',   'name' => 'NEW BRIGHTON SCHOOL OF THE PHILIPPINES, INC.',                             'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12066',   'name' => 'SOUTHERN BAPTIST COLLEGE',                                                 'type' => 'Private', 'region_id' => $r12],
            ['uii' => '11038',   'name' => "KING'S COLLEGE OF MARBEL, INC.",                                           'type' => 'Private', 'region_id' => $r12],
            ['uii' => '12161',   'name' => 'PACIFIC SOUTHBAY COLLEGE, INC.',                                           'type' => 'Private', 'region_id' => $r12],

            // ── BARMM ────────────────────────────────────────────────────
            ['uii' => '15019',   'name' => 'ADIONG MEMORIAL STATE COLLEGE',                                            'type' => 'SUC',     'region_id' => $barmm],
            ['uii' => '12006',   'name' => 'COTABATO STATE UNIVERSITY',                                                'type' => 'SUC',     'region_id' => $barmm],
            ['uii' => '15006',   'name' => 'MINDANAO STATE UNIVERSITY - MAGUINDANAO',                                  'type' => 'SUC',     'region_id' => $barmm],
            ['uii' => '12040',   'name' => 'MINDANAO STATE UNIVERSITY-MAIN CAMPUS MARAWI CITY',                        'type' => 'SUC',     'region_id' => $barmm],
            ['uii' => '12030',   'name' => 'MINDANAO STATE UNIVERSITY-LANAO NATIONAL COLLEGE OF ARTS AND TRADES',      'type' => 'SUC',     'region_id' => $barmm],
            ['uii' => '15070',   'name' => "AL BANGSAMORO SHARI'AH AND PROFESSIONAL EDUCATION COLLEGE",                'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15071',   'name' => 'AS-SALIHEIN INTEGRATED SCHOOL FOUNDATION, INC.',                           'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15054',   'name' => 'BAI MALGEN MAMA COLLEGE',                                                  'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15038',   'name' => 'CALI PARAMEDICAL COLLEGE FOUNDATION',                                      'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15031',   'name' => 'DANSALAN POLYTECHNIC COLLEGE',                                             'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '12095',   'name' => 'DATU MALA MUSLIM MINDANAO ISLAMIC COLLEGE FOUNDATION',                     'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15037',   'name' => 'DATU IBRAHIM PAGLAS MEMORIAL COLLEGE',                                     'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15023',   'name' => 'DEL SUR GOOD SHEPHERD COLLEGE',                                            'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15055',   'name' => 'EASTERN KUTAWATO COLLEGE',                                                 'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15066',   'name' => 'ENTHUSIASTIC COLLEGE',                                                     'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15001',   'name' => 'GANI L. ABPI COLLEGE',                                                     'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15068',   'name' => 'HADJI DATU SAIDONA PENDATUN FOUNDATION COLLEGE',                           'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15061',   'name' => 'ILLANA BAY INTEGRATED COMPUTER COLLEGE',                                   'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15063',   'name' => 'IRANUN FOUNDATION COLLEGE',                                                'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '12021',   'name' => 'JAMIATU MARAWI AL-ISLAMIA FOUNDATION',                                     'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '12022',   'name' => 'JAMIATU MUSLIM MINDANAO',                                                  'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '12023',   'name' => 'JAMIATUL PHILIPPINE AL-ISLAMIA',                                           'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15062',   'name' => 'KHADIJAH MOHAMMAD ISLAMIC ACADEMY',                                        'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15049',   'name' => 'LAKE LANAO COLLEGE',                                                    'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15064',   'name' => 'LANAO CENTRAL COLLEGE',                                                    'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15028',   'name' => 'LANAO EDUCATIONAL INSTITUTE',                                              'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15047',   'name' => 'LANAO ISLAMIC PARAMEDICAL COLLEGE FOUNDATION',                             'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '12034',   'name' => 'MAPANDI MEMORIAL COLLEGE',                                                 'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '12035',   'name' => 'MARAWI CAPITOL COLLEGE FOUNDATION',                                        'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15040',   'name' => 'MARAWI ISLAMIC COLLEGE',                                                   'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '12087',   'name' => 'MINDANAO ISLAMIC COMPUTER COLLEGE',                                        'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15057',   'name' => 'MINDANAO INSTITUTE OF HEALTHCARE PROFESSIONALS',                           'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15010',   'name' => 'PARANG FOUNDATION COLLEGE',                                                'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15060',   'name' => 'PHILIPPINE ENGINEERING AND AGRO-INDUSTRIAL COLLEGE',                       'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15032',   'name' => "PHILIPPINE MUSLIM TEACHERS' COLLEGE",                                      'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15056',   'name' => 'RC-AL KHWARIZMI INTERNATIONAL COLLEGE FOUNDATION',                         'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15041',   'name' => 'SAFRULLAH M. DIPATUAN FOUNDATION ACADEMY',                                 'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15033',   'name' => 'SAL FOUNDATION COLLEGE',                                                   'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '12102',   'name' => 'SENATOR NINOY AQUINO COLLEGE FOUNDATION-MARAWI',                           'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15011',   'name' => 'SHARIFF KABUNSUAN COLLEGE (ANNEX)',                                        'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15036',   'name' => 'SPA COLLEGE',                                                              'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15043',   'name' => 'ST. BENEDICT COLLEGE OF MAGUINDANAO',                                      'type' => 'Private', 'region_id' => $barmm],
            ['uii' => '15012',   'name' => 'SULTAN KUDARAT ISLAMIC ACADEMY FOUNDATION COLLEGE',                        'type' => 'Private', 'region_id' => $barmm],
        ];

        foreach ($heis as $hei) {
            HEI::updateOrCreate(
                ['uii' => $hei['uii']],
                array_merge($hei, ['status' => 'active', 'code' => null])
            );
        }
    }
}
