import { Badge } from '@/components/ui/badge';
import { Database, Sparkles, Wrench } from 'lucide-react';

const toolLabels: Record<string, string> = {
    get_liquidation_summary: 'Liquidation Summary',
    list_liquidations: 'Liquidation Records',
    find_liquidation: 'Liquidation Lookup',
    list_heis: 'HEI Catalog',
    list_reference_data: 'Reference Data',
};

/**
 * Compact provenance row shown above an assistant answer.
 *
 * Each unique tool that contributed to the reply becomes a pill, alongside
 * a "Local Database" anchor pill and an "AI insight" tag. Renders nothing
 * if no tools were called (the assistant answered from prompt alone).
 */
export function Sources({ tools }: { tools: string[] }) {
    const unique = Array.from(new Set(tools.filter(Boolean)));

    if (unique.length === 0) return null;

    return (
        <div className="flex flex-wrap items-center gap-1.5">
            <Badge
                variant="secondary"
                className="gap-1 font-normal"
                title="Queried directly from the UniFAST MySQL database"
            >
                <Database className="h-3 w-3" />
                Local Database
            </Badge>
            {unique.map((tool) => (
                <Badge
                    key={tool}
                    variant="outline"
                    className="gap-1 font-normal"
                    title={`MCP tool: ${tool}`}
                >
                    <Wrench className="h-3 w-3" />
                    {toolLabels[tool] ?? tool}
                </Badge>
            ))}
            <Badge
                variant="outline"
                className="gap-1 font-normal text-muted-foreground"
                title="Narrative commentary generated by the AI model"
            >
                <Sparkles className="h-3 w-3" />
                AI insight
            </Badge>
        </div>
    );
}
